// Builds js/ui/icon-sprite.js from Tabler outline SVGs (MIT).
// Usage: npm pack @tabler/icons && tar xzf tabler-icons-*.tgz && node tools/build-icons.mjs package/icons/outline
import fs from 'fs';
import path from 'path';
import { ICONS } from '../js/ui/icons.js';

const dir = process.argv[2];
if (!dir) {
  console.error('usage: node tools/build-icons.mjs <tabler outline dir>');
  process.exit(1);
}
const symbols = Object.entries(ICONS).map(([key, name]) => {
  const svg = fs.readFileSync(path.join(dir, name + '.svg'), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
    .replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*\/>/, '').replace(/\s+/g, ' ').trim();
  return `<symbol id="i-${key}" viewBox="0 0 24 24">${inner}</symbol>`;
});
const out = `// Generated by tools/build-icons.mjs from Tabler Icons (MIT, https://tabler.io/icons). Do not edit.\nexport const SPRITE = '<svg xmlns="http://www.w3.org/2000/svg">${symbols.join('')}</svg>';\n`;
fs.writeFileSync(new URL('../js/ui/icon-sprite.js', import.meta.url), out);
console.log(`${symbols.length} icons`);
